name: email_auth
description: A Flutter package to verify emails using OTP based method, to make sure we get real world data.
version: 0.0.1+1.7
homepage: https://github.com/saran-surya/email_auth.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
